---
title: "Analysis_script"
editor: visual
date: today
toc: false
abstract-title: "Research question:"
abstract: "Does ICS-X lead to a greater improvement of forced expiratory volume (FEV1) compared to a standard inhaler in patients with milkd and persistent asthma?"
format:
  html:
    embed-resources: true 
    number-sections: true 
    code-fold: show 
    
editor_options:
  chunk_output_type: console
execute:
  
  warning: false 
  message: false
---

## Effect of a New Inhaled Therapy on Lung Function in Mild Asthma

A randomized controlled trial evaluates a new inhaled corticosteroid (ICS-X) compared to a standard inhaler in patients with mild persistent asthma.

Patients are randomized to receive either ICS-X or standard therapy for 6 weeks. Lung function is assessed at baseline and at follow-up using FEV₁ (forced expiratory volume in 1 second).

***The primary endpoint is improvement in FEV₁.***

### Variables

-   *Outcome:*

    fev1_improvement: change in FEV₁ (liters) from baseline to 6 weeks

-   *Continuous predictors:*

    -   age: patient age (years)
    -   baseline_fev1: baseline FEV₁ (liters)

-   Categorical predictors:

    -   treatment_group: randomized treatment ("standard_inhaler", "ICSX")

    -   smoking_status: smoking status ("never", "former", "current")

### Hypotheses:

-   ICS-X leads to greater improvement in FEV₁
-   Higher baseline FEV₁ is associated with less room for improvement
-   Smokers exhibit a reduced treatment response
-   A negative Age effect on improvement

## Data Import and Screening

```{r}
#| ouput: false
#| echo: false

rm(list = ls())

# Import necessary libraries
  library(performance)
  library(pastecs)
  library(car)
  library(ggplot2)
  library(ggpubr)
  library(ggeffects)
  library(GGally)
  library(tidyverse)
  library(glue)

# load data
dd <- read.csv("data/processed/lung-function.csv", stringsAsFactors = T)

# Screen data
str(dd)
summary(dd)

# Check for NA's
sum(is.na(dd)) # No NA

# Check balanced RCT design
table(dd$treatment_group)
```
